name: BuildAndTest

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      # 빌드 스텝 실행
      - name: Build Application
        run: |
          set -eo pipefail
          xcodebuild clean build \
            -project BestWish.xcodeproj \
            -scheme BestWish \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            | xcbeautify
